OpenShift Management role
rhtconsulting/rhc-ose pull request #234
Opened 2016-09-23 04:27 UTC by sabre1041

#### What does this PR do?

Adds an Ansible role for performing ongoing management and ensuring stability of the OpenShift environment

#### How should this be manually tested?

Create an inventory file with an openshift group containing an OpenShift master similar to the following:

```
[openshift]
<openshift-host>
```

Obtain the OAuth token of a user with `cluster-admin` rights

Execute the role from the root of the `rhc-ose-ansible` folder to prune builds, deployments and images:

```
ansible-playbook -i inventory/openshift-management -e "openshift_token=<token> openshift_prune_images=True openshift_prune_builds=True openshift_prune_deployments=True"  playbooks/openshift-management.yml
```

#### Is there a relevant Issue open for this?
No

#### Who would you like to review this?
/cc @etsauer  @oybed

2016-11-14 22:02 UTC, JayKayy requested changes
Initial review and testing

2016-11-14 22:02 UTC, JayKayy commented on rhc-ose-ansible/roles/openshift-management/tasks/main.yml
> +  shell: oc login --token={{ openshift_token }} {{ openshift_login_insecure_flag }} {{ openshift_master_url }}
If we are using the token to login would it be better to not use login and just use the commands you normally would with the --token option? e.g. `oc adm prune deployments.... --token=<token>`

2016-11-14 22:02 UTC, JayKayy commented on rhc-ose-ansible/roles/openshift-management/defaults/main.yml
> +openshift_login_insecure: False
Where is this used? Should a conditional use this variable as to whether the `openshift_login_insecure_flag` should be used?

2016-11-14 22:02 UTC, JayKayy commented on rhc-ose-ansible/roles/openshift-management/defaults/main.yml
> +openshift_prune_builds_keep_younger: 1h0m0s
Not really an issue but isn't the default of 1hr a bit small of a window? I figured this should be something like a few days. Please explain if its not just a placeholder.

2016-11-14 22:02 UTC, JayKayy commented on rhc-ose-ansible/roles/openshift-management/tasks/main.yml
> +  set_fact: kubeconfig="/tmp/openshift-management-{{ ansible_date_time.epoch }}/config"
This is a solid method of not interrupting the current login by creating a temporary config file. However, I'm noticing that if this playbook fails for any reason, the handler will not clean up the login config. In this instance you will have a cluster-admin credential in a public /tmp/ maintenance folder for any user to point their oc client at and gain cluster-admin rights. Maybe this should default to somewhere in /root/?

2016-11-15 05:14 UTC, sabre1041 commented on rhc-ose-ansible/roles/openshift-management/defaults/main.yml
> +openshift_login_insecure: False
the `openshift_login_insecure_flag` is used during the login play as it is a parameter to the `oc login` command

2016-11-15 05:16 UTC, sabre1041 commented on rhc-ose-ansible/roles/openshift-management/defaults/main.yml
> +openshift_prune_builds_keep_younger: 1h0m0s
This is the default value as per the [OpenShift Docs](https://docs.openshift.com/container-platform/3.3/admin_guide/pruning_resources.html#pruning-images). Can refine the default value if necessary. User has the ability to override the default value if desired

2016-11-15 05:21 UTC, sabre1041 commented on rhc-ose-ansible/roles/openshift-management/tasks/main.yml
> +  shell: oc login --token={{ openshift_token }} {{ openshift_login_insecure_flag }} {{ openshift_master_url }}
If the token can be utilized in this manner, the entire login step/management could be eliminated

2016-11-15 13:54 UTC, JayKayy commented on rhc-ose-ansible/roles/openshift-management/defaults/main.yml
> +openshift_login_insecure: False
I was more talking about `openshift_login_insecure`  seems to be a variable set without any references to it.

2016-11-15 14:31 UTC, JayKayy commented on rhc-ose-ansible/roles/openshift-management/tasks/main.yml
> +  shell: oc login --token={{ openshift_token }} {{ openshift_login_insecure_flag }} {{ openshift_master_url }}
As you pointed out the login step provides flexibility of selecting the master url instead of expecting and requiring a preconfigured master.

2016-11-15 15:09 UTC, etsauer commented
@sabre1041 shouldn't this PR move over to https://github.com/redhat-cop/casl-ansible

2016-11-15 16:06 UTC, oybed commented
@sabre1041 @etsauer yes, it should be moved. Do we want to finish the review here, or move it first, then finalize the review? I'm good with this change and would like to see it merged sooner than later as we can benefit from this in many places.

2016-11-15 16:08 UTC, sabre1041 commented
@oybed. Yep it should be moved for sure. Since @JayKayy suggested some enhancements that could be made, why dont we move now and create a PR in `casl-ansible` and migrate the comments from this PR so that they and the work are tracked for the long term

2016-11-15 16:16 UTC, oybed commented
@sabre1041 sounds like a good plan - can you please open the PR in the redhat-cop repo?

2016-11-15 16:34 UTC, sabre1041 commented
@oybed @JayKayy @etsauer 

PR created in *casl-ansible*

https://github.com/redhat-cop/casl-ansible/pull/4

2016-11-15 16:35 UTC, closed without merging